---
title: "p8105_hw5_jt3098"
author: "Jieqi Tu (jt3098)"
date: "11/4/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
```

## Problem 1
```{r file names defining}
# Create a data frame that contains all file names
longitudinal_data = 
  tibble(list.files(path = "./data"))

# Rename the column name of the first variable
colnames(longitudinal_data)[1] = 'file'
```

```{r read in files}
# Create a function to read in files
read_data = function(file) {
  data = 
    read.csv(str_c("./data/", file)) %>%
    as.data.frame()
  
 data
}

# Load files in using created function above
longitudinal_data =
  longitudinal_data %>%
  mutate(data = map(longitudinal_data$file, read_data)) # All data from one file are nested in one variable called "data"
```

```{r data tidying}
# Spread out the data set
longitudinal_data = 
  longitudinal_data %>%
  unnest() %>% # unnest the `data` variable to obtain more variables to store the data
  gather(key = week, value = value, week_1:week_8) # make week be a single variable

# Separate the control and experiment groups
longitudinal_data = 
  longitudinal_data %>%
  separate(file, into = c("group_type", "number"), sep = "_") %>%
  separate(number, into = c("ID", "extension"), sep = 2) %>%
  select(-extension)

# Manipulate the "week" variable
longitudinal_data = 
  longitudinal_data %>%
  separate(week, into = c("character", "week_number"), sep = 5) %>%
  select(-character)

# Revise the name of arms
longitudinal_data$group_type = str_replace(longitudinal_data$group_type, "con", "control")
longitudinal_data$group_type = str_replace(longitudinal_data$group_type, "exp", "experimental")

# Change the column type of "week_number"
longitudinal_data$week_number = as.numeric(longitudinal_data$week_number)
```

```{r speghetti plot for problem 1}
# Make a new variable for each subject to have a more clear order
longitudinal_data$subject = str_c(longitudinal_data$group_type, '_', longitudinal_data$ID)

# Make a speghetti plot to show the trend of observation data from each arm
longitudinal_data %>%
  ggplot(aes(x = week_number, y = value, group = subject, color = group_type)) +
  geom_line(alpha = 0.5) + 
  geom_point(alpha = 0.2) +
  labs(
    title = "Observations on Each Subject Over Time",
    x = "Week",
    y = "Observation Data"
  ) +
  theme_bw()
```

